name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Archive
        run: |
          zip -r offical-theme-v2.zip index.html ./css ./js
          mv offical-theme-v2.zip offical-theme-v2.bbgtheme2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: offical-theme-v2 ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: offical-theme-v2.bbgtheme2